// src/lib/quotes.ts
// Contains the list of quotes for the daily quote feature.

export interface Quote {
  text: string;
  author: string;
}

export const allQuotes: Quote[] = [
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "The beginning is the most important part of the work.", author: "Plato" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "It is not living that matters, but living rightly.", author: "Socrates" },
  { text: "The only good is knowledge and the only evil is ignorance.", author: "Socrates" },
  { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
  { text: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso" },
  { text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "He who knows others is wise; he who knows himself is enlightened.", author: "Lao Tzu" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "The best way out is always through.", author: "Robert Frost" },
  { text: "In three words I can sum up everything I’ve learned about life: it goes on.", author: "Robert Frost" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It’s not the load that breaks you down, it’s the way you carry it.", author: "Lou Holtz" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Out of difficulties grow miracles.", author: "Jean de La Bruyère" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "Start where you stand, and work with whatever tools you may have.", author: "Napoleon Hill" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Growth begins when we begin to accept our own weakness.", author: "Jean Vanier" },
  { text: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
  { text: "Life is a mystery which must be lived, not a problem to be solved; thus, embrace each moment as it comes with courage and curiosity.", author: "Søren Kierkegaard" },
  { text: "To live is to suffer, to survive is to find some meaning in the suffering, and to thrive is to create that meaning yourself.", author: "Friedrich Nietzsche" },
  { text: "What need is there to weep over parts of life? The whole of it calls for tears—yet through those tears, we forge our strength.", author: "Seneca" },
  { text: "The soul becomes dyed with the color of its thoughts, so let us paint it with hues of hope and determination.", author: "Marcus Aurelius" },
  { text: "Freedom is not the absence of commitments, but the ability to choose—and to commit myself to—what is best for me.", author: "Paulo Coelho" },
  { text: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes to see what is already before us.", author: "Marcel Proust" },
  { text: "To dare is to lose one’s footing momentarily; not to dare is to lose oneself entirely in the safety of the known.", author: "Søren Kierkegaard" },
  { text: "He who has a why to live can bear almost any how, for purpose is the flame that lights the darkest paths.", author: "Friedrich Nietzsche" },
  { text: "Virtue is not left to stand alone; he who practices it will have neighbors, for goodness inspires action in others.", author: "Confucius" },
  { text: "The art of living well and the art of dying well are one, both requiring us to embrace each day as a step toward wisdom.", author: "Epicurus" },
  { text: "Many lack the originality to lack originality, yet true growth begins when we break free from the mold of others’ expectations.", author: "Karl Kraus" },
  { text: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", author: "Jean-Paul Sartre" },
  { text: "Existence precedes essence, and thus we are the sculptors of our own being through the choices we make each day.", author: "Jean-Paul Sartre" },
  { text: "The first step toward wisdom is to call things by their right names, and the second is to act upon that clarity.", author: "Confucius" },
  { text: "The wise man does at once what the fool does finally, for procrastination is the thief of both time and virtue.", author: "Baltasar Gracián" },
  { text: "The energy of the mind is the essence of life, and to direct it toward noble ends is the highest human endeavor.", author: "Aristotle" },
  { text: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.", author: "Immanuel Kant" },
  { text: "What does not kill me makes me stronger, for in struggle we find the path to greatness.", author: "Friedrich Nietzsche" },
  { text: "It does not matter how slowly you go as long as you do not stop, for persistence is the mother of all achievement.", author: "Confucius" },
  { text: "One is not born, but rather becomes, a woman; and so too, one becomes the architect of one's own life.", author: "Simone de Beauvoir" },
  { text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author: "Epicurus" },
  { text: "The universe is change; our life is what our thoughts make it—embrace both, and you will master both.", author: "Marcus Aurelius" },
  { text: "A journey of a thousand miles begins with a single step, and each step brings us closer to our true selves.", author: "Lao Tzu" },
  { text: "To venture causes anxiety, but not to venture is to lose one's self... And to venture in the highest sense is precisely to become conscious of oneself.", author: "Søren Kierkegaard" },
  { text: "The miracle that saves the world, the realm of human affairs, from its normal, 'natural' ruin is ultimately the fact of natality, in which the faculty of action is ontologically rooted.", author: "Hannah Arendt" },
  { text: "The main interest in life and work is to become someone else that you were not in the beginning.", author: "Michel Foucault" },
  { text: "Attention is the rarest and purest form of generosity, and through it, we can transform both ourselves and the world.", author: "Simone Weil" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { text: "Being-toward-death is the anticipation of a potentiality-for-Being which is not to be outstripped.", author: "Martin Heidegger" },
  { text: "The very relationship with the other is the relationship with the future.", author: "Emmanuel Levinas" },
  { text: "Repetition is not generality; it is the power of difference to produce the new.", author: "Gilles Deleuze" },
  { text: "There is nothing outside the text, but within it lies the infinite possibility of meaning.", author: "Jacques Derrida" },
  { text: "There is no gender identity behind the expressions of gender; identity is performatively constituted by the very 'expressions' that are said to be its results.", author: "Judith Butler" },
  { text: "The only way to be truly free is to confront the abyss of freedom itself.", author: "Slavoj Žižek" },
  { text: "A truth is something that happens, not something that is; it is an event that demands our fidelity.", author: "Alain Badiou" },
  { text: "Human beings are not just rational agents; they are also emotional, social, and imaginative creatures, and their flourishing requires the development of all these capacities.", author: "Martha Nussbaum" },
  { text: "Development consists of the removal of various types of unfreedoms that leave people with little choice and little opportunity of exercising their reasoned agency.", author: "Amartya Sen" },
  { text: "The moment we choose to love we begin to move against domination, against oppression. The moment we choose to love we begin to move towards freedom, to act in ways that liberate ourselves and others.", author: "bell hooks" },
  { text: "I cannot be an optimist but I am a prisoner of hope.", author: "Cornel West" },
  { text: "You have to act as if it were possible to radically transform the world. And you have to do it all the time.", author: "Angela Davis" },
  { text: "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.", author: "Audre Lorde" },
  { text: "I change myself, I change the world.", author: "Gloria Anzaldúa" },
  { text: "The intellectual's role is to speak the truth, as plainly, directly, and as honestly as possible.", author: "Edward Said" },
  { text: "Imperialism leaves behind germs of rot which we must clinically detect and remove from our land but from our minds as well.", author: "Frantz Fanon" },
  { text: "Education either functions as an instrument which is used to facilitate integration of the younger generation into the logic of the present system and bring about conformity or it becomes the practice of freedom, the means by which men and women deal critically and creatively with reality and discover how to participate in the transformation of their world.", author: "Paulo Freire" },
  { text: "Most learning is not the result of instruction. It is rather the result of unhampered participation in a meaningful setting.", author: "Ivan Illich" },
  { text: "I study myself more than any other subject. That is my metaphysics, that is my physics.", author: "Michel de Montaigne" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", author: "Blaise Pascal" },
  { text: "The highest activity a human being can attain is learning for understanding, because to understand is to be free.", author: "Baruch Spinoza" },
  { text: "Reason is, and ought only to be the slave of the passions, and can never pretend to any other office than to serve and obey them.", author: "David Hume" },
  { text: "No man's knowledge here can go beyond his experience.", author: "John Locke" },
  { text: "Man is born free, and everywhere he is in chains. One man thinks himself the master of others, but remains more of a slave than they are.", author: "Jean-Jacques Rousseau" },
  { text: "Think for yourselves and let others enjoy the privilege to do so too.", author: "Voltaire" },
  { text: "I do not wish them [women] to have power over men; but over themselves.", author: "Mary Wollstonecraft" },
  { text: "The only freedom which deserves the name is that of pursuing our own good in our own way, so long as we do not attempt to deprive others of theirs, or impede their efforts to obtain it.", author: "John Stuart Mill" },
  { text: "Believe that life is worth living and your belief will help create the fact.", author: "William James" },
  { text: "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.", author: "Bertrand Russell" },
  { text: "The limits of my language mean the limits of my world.", author: "Ludwig Wittgenstein" },
  { text: "The body is our general medium for having a world.", author: "Maurice Merleau-Ponty" },
  { text: "The life of man is of no greater duration than the breath of his nostrils, yet within that span, he may achieve wonders through resolve.", author: "Thomas Hobbes" },
  { text: "The history of the world is none other than the progress of the consciousness of freedom.", author: "G.W.F. Hegel" },
  { text: "To begin with, we must turn our gaze inward, for only through reflection do we uncover the essence of our being.", author: "Edmund Husserl" },
  { text: "The only constant is change, and to live well is to dance with the flux of existence.", author: "Heraclitus" },
  { text: "The first and greatest victory is to conquer yourself; to be conquered by yourself is of all things most shameful and vile.", author: "Plato" }
];
